### ISSUE TITLE
Arguments to Spring cloud Task Launcher are not parsed correctly

### ISSUE THREAD

**Issue by mudduvenkatesh** [spring-guides/gs-spring-cloud-task#10]
I have the following args to pass to Cloud Task that are canonical Uri.. 
http://dataflow-server:9393/tasks/executions/launch?
name=SDF-KG-DATAUNIFICATION-SERVICE-TASK&
arguments=
--file-name-path=uploads/nucc-200.txt 
--process-job-specification-uri=http://metadata.mypharma.net/dujob#64lwpdp3stgs4y0gwq
--supplier-interface-specification-uri=http://metadata.mypharma.net/datainterface#vra14arsx5n7v80dq9
--run-timestamp=2024-04-05T11:07:00.000 
--business-date=2024-04-05

When trying to get them in Cloud task I get http://metadata.mypharma.net/dujob for **process-job-specification-uri,** cutting off the fragment #64lwpdp3stgs4y0gwq

Am I doing anything wrong? and any suggestions

**Comment by robertmcnees** [comment]
Hi @mudduvenkatesh. I don't think this issue is related to the guide. A better place for this question is stackoverflow. You will be able to get more eyes looking at your issue if you use that site instead. Closing the issue.
