### ISSUE TITLE
Update Spring Boot version

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-spring-cloud-task#5]
Upgrade the guide to the most recent Spring Boot version.  The latest version of Spring Boot can be found on [the Spring Boot project page](https://spring.io/projects/spring-boot#learn). Look for the release with the `CURRENT` tag.  Milestones (M) and SNAPSHOT releases should not be used in the guide.  
Alternatively you can also find the latest version of Spring boot by looking on [start.spring.io](https://start.spring.io/).

The following files will need changed:

`complete/task/pom.xml`
`initial/task/pom.xml`

**Comment by vimal-java-dev** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by robertmcnees** [comment]
Hi @vimalJD .  Yes, this project is ongoing.  This is the repo behind the [Task guide on spring.io](https://spring.io/guides/gs/spring-cloud-task/).

**Comment by vimal-java-dev** [comment]
> Hi @vimalJD . Yes, this project is ongoing. This is the repo behind the [Task guide on spring.io](https://spring.io/guides/gs/spring-cloud-task/).

I have been working on it, could you please assign to me this issue as **"good first issue"**?

**Comment by robertmcnees** [comment]
Hi @vimalJD .  Please feel free to submit a PR for this issue.  We will merge the first valid PR that comes through.

If you don't get the chance to work on this issue there should be other opportunities.  Spring Boot releases approximately once per month so frequent updates will be needed.  Additionally this same issue exists in about 16 other repositories in the spring-guides org.

Thanks again for your interest!  If you need help learning the processes [here is a great video](https://www.youtube.com/watch?v=kHZzQR9ntvc) by two Spring Engineers on how to contribute to open source.  One of the presenters just so happens to be the lead for the Spring Cloud Task project.

**Comment by vimal-java-dev** [comment]
> Hi @vimalJD . Please feel free to submit a PR for this issue. We will merge the first valid PR that comes through.
> 
> If you don't get the chance to work on this issue there should be other opportunities. Spring Boot releases approximately once per month so frequent updates will be needed. Additionally this same issue exists in about 16 other repositories in the spring-guides org.
> 
> Thanks again for your interest! If you need help learning the processes [here is a great video](https://www.youtube.com/watch?v=kHZzQR9ntvc) by two Spring Engineers on how to contribute to open source. One of the presenters just so happens to be the lead for the Spring Cloud Task project.


- I am working on it.

![Docker-Image](https://github.com/spring-guides/gs-spring-cloud-task/assets/91485321/9c0870c7-5ccf-4b46-9db9-ad94392da168)

**Comment by vimal-java-dev** [comment]
1. I opened up a project in the Spring tool suite, how to run the project?
 
2. Should I need to convert it into a Maven project?

**Comment by robertmcnees** [comment]
Closing this issue for now as Boot has been upgraded to the latest version.  There will likely be new opportunities to contribute in the future.

**Comment by vimal-java-dev** [comment]
Thanks, To **assign** this issue.
