### ISSUE TITLE
Select query for task_execution does not execute

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-spring-cloud-task#7]
The documentation states:

`select * from task_execution;`

However the table `task_execution` must be capitalized.  The documentation should read:

`select * from TASK_EXECUTION;`

**Comment by vimal-java-dev** [comment]
> The documentation states:
> 
> `select * from task_execution;`
> 
> However the table `task_execution` must be capitalized. The documentation should read:
> 
> `select * from TASK_EXECUTION;`

Can you provide a specific link, which documentation need to folllow?

**Comment by robertmcnees** [comment]
The change can be made in the [README](https://github.com/spring-guides/gs-spring-cloud-task/blob/main/README.adoc).  The guide is published on [spring.io](https://spring.io/guides/gs/spring-cloud-task/).

**Comment by vimal-java-dev** [comment]
> The change can be made in the [README](https://github.com/spring-guides/gs-spring-cloud-task/blob/main/README.adoc). The guide is published on [spring.io](https://spring.io/guides/gs/spring-cloud-task/).

- My PR is ready for review,
https://github.com/spring-guides/gs-spring-cloud-task/pull/9

**Comment by vimal-java-dev** [comment]
> The change can be made in the [README](https://github.com/spring-guides/gs-spring-cloud-task/blob/main/README.adoc). The guide is published on [spring.io](https://spring.io/guides/gs/spring-cloud-task/).

Could you please review it?

https://github.com/spring-guides/gs-spring-cloud-task/pull/9#pullrequestreview-1660642026

**Comment by robertmcnees** [comment]
Looks good. Thanks for the PR. I merged in the PR so I am closing this issue.

**Comment by vimal-java-dev** [comment]
> Looks good. Thanks for the PR. I merged in the PR so I am closing this issue.

👍👍👍
